version: "3"

volumes:
  database:
    driver: local

services:
  a0e-bot:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    volumes:
      - database:/code/database
